/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\island_sand_texture.glb --precision=6
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/island_sand_texture.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Stylized Sand']} scale={[10, 1, 10]} />
    </group>
  )
}

useGLTF.preload('/island_sand_texture.glb')
